name: Fix JSON files

on:
  workflow_dispatch:

jobs:
  fix-json:
    runs-on: ubuntu-latest
    steps:
        # download the files
      - name: Checkout code
        uses: actions/checkout@v4

        # jsonrepair runs on node
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

        # install library that fixes json errors
      - name: install jsonrepair
        id: jsonrepair-install
        run: |
            npm install -g jsonrepair
        
      - name: Get changed files from the last 40 commits
        id: changed-files
        run: |
          git fetch --unshallow
          git diff HEAD~40 --name-only > changed_files.txt
          cat -n changed_files.txt
    
      - name: Read and process changed files
        run: |
          while IFS= read -r file; do
            if [[ "$file" == *".json" ]];then
              jsonrepair "$file" --overwrite
              echo "Processed file: $file"
            fi
          done < changed_files.txt
          rm -rf changed_files.txt
          jsonrepair data/_list.json --overwrite
          jsonrepair data/_packs.json --overwrite
          jsonrepair data/_staff.json --overwrite
        

        # save
      - name: Commit files # only runs if something actually changed
        run: |
          if [[ -n "$(git status -s)" ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Actions"
            git commit -m "CI: fix json errors" -a
          else
            echo "No changes made!"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}